# Generated by Django 3.2.4 on 2021-06-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_delete_fundraiser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
