# Generated by Django 3.2.4 on 2021-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
