# Generated by Django 3.2.4 on 2021-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Country_code',
            field=models.IntegerField(default=91),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='Phone_Number',
            field=models.IntegerField(null=True),
        ),
    ]
