# Generated by Django 3.2.4 on 2021-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_campaign_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Amount_Reached',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Amount_Wanted',
            field=models.IntegerField(null=True),
        ),
    ]
