# Generated by Django 3.2.4 on 2021-06-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_auto_20210625_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Currency_Name',
            field=models.CharField(default='Rupee', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Currency_Symbol',
            field=models.CharField(default='$', max_length=100),
        ),
    ]
