# Generated by Django 3.2.4 on 2021-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0014_auto_20210625_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='Currency_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='Currency_Symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
