# Generated by Django 3.2.4 on 2021-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0016_auto_20210625_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('images', models.FileField(blank=True, upload_to='pics')),
            ],
        ),
    ]
