# Generated by Django 3.2.4 on 2021-06-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0018_auto_20210628_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='File',
            field=models.FileField(blank=True, upload_to='files_db'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Image',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
