# Generated by Django 3.2.4 on 2021-07-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0022_auto_20210703_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetail',
            name='Categoary',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
